name: Upload Base Assets to S3

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  upload-assets:
    name: Sync base assets to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Update lockfile
        run: uv lock

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Run sync base assets
        run: uv run scripts/manage.py sync-assets --upload-base
